fix(web-app): various small bugs
carbon-design-system/carbon-platform pull request #1004
Opened 2022-07-12 13:28 UTC by alisonjoseph

Closes #974 
- fix top spacing
http://localhost:3000/elements/icons/library
http://localhost:3000/elements/pictograms/library

Closes #968 
- Update image path to higher res image, delete duplicate
http://localhost:3000/developing

Closes #964 
- fix spelling error
http://localhost:3000/

2022-07-12 14:27 UTC, francinelucca requested changes
mostly LGTM, small CR

2022-07-12 14:27 UTC, francinelucca commented on services/web-app/components/svg-libraries/svg-library.module.scss
> +  padding-top: spacing.$spacing-05;
Still see a small padding difference with carbondesignsystem.com, I think it should be spacing-07 here
```suggestion
  padding-top: spacing.$spacing-07;
```

2022-07-12 14:45 UTC, francinelucca approved these changes
💃 🚀

2022-07-14 16:24 UTC, andreancardona approved these changes
yay! looks good

2022-07-14 16:24 UTC, merged