fix: udpates to how carbon works
carbon-design-system/carbon-platform pull request #1029
Opened 2022-07-18 21:09 UTC by aubrey-oneal

Relates #941 

#### Changelog

**Changed**
- Content changes to How Carbon Works based on our updated naming convention.
- Updated ecosystem image (this image is semi-finalized)

#### Testing / reviewing

Request for content review

2022-07-18 21:10 UTC, aubrey-oneal commented
I have read the DCO document and I hereby sign the DCO.

2022-07-19 00:56 UTC, andreancardona approved these changes
Looks good to me! :)

2022-07-19 08:22 UTC, yumeforever commented
@aubrey-oneal To me it looks great, I like how you reworded libraries, design kits, and assets. Pretty good!

2022-07-19 13:37 UTC, kingtraceyj requested changes
just a small apostrophe update! it's looking really good.

i don't have my dev environment set up currently so i can't look at the image in context. we usually export the image at 2x to make sure the resolution is ok.

2022-07-19 13:37 UTC, kingtraceyj commented on services/web-app/pages/about-carbon/how-carbon-works.mdx
> +consistent user experiences that meet IBM`s standards.
```suggestion
consistent user experiences that meet IBM's standards.
```

a small apostrophe update!

2022-07-19 14:59 UTC, merged