feat(web-app): side nav ia updates
carbon-design-system/carbon-platform pull request #1111
Opened 2022-08-02 20:58 UTC by alisonjoseph

Closes #1037

#### Testing / reviewing

Check that side nav matches #1037 and that all links work correctly

Question for @aubrey-oneal - should the url change now that we are nesting the catalogs inside of an assets header in the nav
http://localhost:3000/catalogs/functions
to
http://localhost:3000/catalogs/assets/functions ??

2022-08-03 14:24 UTC, francinelucca approved these changes
💃 💃

2022-08-03 14:44 UTC, mattrosno commented
@alisonjoseph no opinion here if we update our asset catalog URLs to have `/assets`.

2022-08-03 18:29 UTC, alisonjoseph commented
@mattrosno that also means we will end up with assets twice in the url for the detail pages, so maybe we leave as is, without complicating the url further.

2022-08-03 19:29 UTC, mattrosno commented
@alisonjoseph detail pages are under `/libraries` route, not `/catalogs` route, so we should be good there. Since catalogs are shortcuts to assets that live in libraries.

2022-08-03 20:29 UTC, francinelucca commented
on that same note, should `/libraries` be `/catalogs/libraries` now? since it's insider the catalog? 👀 
I vote yes...

2022-08-04 16:06 UTC, mattrosno commented
@alisonjoseph I think we landed on:

https://next.carbondesignsystem.com/assets/components
https://next.carbondesignsystem.com/libraries
https://next.carbondesignsystem.com/data-visualization

Is that right?

2022-08-04 16:06 UTC, alisonjoseph commented
@mattrosno correct, removing "catalogs" and "collections" from urls

2022-08-04 16:08 UTC, mattrosno commented
Logic: remove `/catalogs` and `/collections` from URLs because those are just headings in the side nav (not clickable.) If we need to add in `/collections` in the future to protect against URL collisions when those are user defined, we can, and would only have to add redirects for the data viz collection.

2022-08-04 16:09 UTC, mattrosno commented
@alisonjoseph and adding `/assets` in the asset catalog routes still? https://next.carbondesignsystem.com/assets/components

2022-08-04 20:24 UTC, francinelucca approved these changes
💃

2022-08-09 16:01 UTC, andreancardona approved these changes
🔥

2022-08-09 18:37 UTC, aubrey-oneal commented on services/web-app/data/nav-data.js
>          title: 'Data vizualization',
change to 'visualization'

2022-08-09 18:40 UTC, aubrey-oneal requested changes
URLs look good! Just need to change 'vizualization' to 'visualization'

2022-08-09 21:17 UTC, merged