fix: add design kit descriptions
carbon-design-system/carbon-platform pull request #1185
Opened 2022-08-29 18:37 UTC by aubrey-oneal

Closes #922 

#### Changelog

**New**

- New design kit descriptions based on our [airtable](https://airtable.com/appyxEkZZl7YQRGDF/tbldsudusc0bxnbLY/viwwXMOknhZYQjeLr?blocks=hide)
- Indexed Figma Gatsby kit

**Changed**

- Minor capitalization fixes

#### Testing / reviewing

- Content review to ensure no mistakes were made in matching descriptions with indexed design kits

2022-08-29 18:56 UTC, jdharvey-ibm approved these changes

2022-08-29 20:04 UTC, mattrosno requested changes

2022-08-29 20:04 UTC, mattrosno commented on packages/resources/carbon.yml
> +      Language
```suggestion
      Language.
```

2022-08-29 20:04 UTC, mattrosno commented on packages/resources/carbon.yml
> +    description: Quickly create and test low fidelity wireframes in Invision Freehand.
```suggestion
    description: Quickly create and test low fidelity wireframes in InVision Freehand.
```

2022-08-30 14:57 UTC, mattrosno approved these changes

2022-08-30 15:30 UTC, merged