feat: set unique meta titles
carbon-design-system/carbon-platform pull request #1577
Opened 2023-01-27 17:58 UTC by mattrosno

Closes #908 
Closes #1576 

{{ Short description }}

#### Changelog

**New**

- {{ New thing }}

**Changed**

- {{ Changed thing }}

**Removed**

- {{ Removed thing }}

#### Testing / reviewing

{{ Add descriptions, steps or a checklist for how reviewers can verify this PR works or not }}

2023-01-31 00:00 UTC, francinelucca requested changes
LGTM!, one minor observation an some cleanup suggestions 🚀

2023-01-31 00:00 UTC, francinelucca commented on services/web-app/utils/seo.js
> +}
To call the recursive function:
```suggestion
/**
 * For a given path like `/about-carbon/how-carbon-works`, if that matches any known nav data,
 * construct a title like "How Carbon works - About Carbon" to ensure all titles are unique. The
 * lowest node in the tree is shown first in the meta title.
 *
 * @param {string} path - typically next/router `asPath`
 * @param {Array} navData - optional nav data for dynamic side navs, e.g. libraries
 * @param {boolean} hasTabs - if the page has page tabs
 * @returns {string}
 */
export const getMetaTitle = (path, navData = [], hasTabs = false) => {
  const allNavData = [...globalNavData, ...standardsNavData, ...assetsNavData, ...navData]

  // if page tabs, pop the last path for the path to match, and all the paths in nav data
  const sideNavPath = getSideNavPath(path, hasTabs)

  return getPageTitle(allNavData, sideNavPath, hasTabs)
}
```

2023-01-31 00:00 UTC, francinelucca commented on services/web-app/utils/seo.js
> +
I feel like doing it recursively is a bit easier to read in this case?, totally optional!:
```suggestion

/**
 * For a given side nav path like `/about-carbon/how-carbon-works`,
 *  if that matches any supplied nav data,
 * construct a title like "How Carbon works - About Carbon" to ensure all titles are unique. The
 * lowest node in the tree is shown first in the meta title.
 *
 * @param {Array} navData - array of all nav items to find sideNavPath in
 * @param {string} sideNavPath - path to side nav item to find
 * @param {boolean} hasTabs - if the page has page tabs
 * @returns {string} title
 */
const getPageTitle = (navData, sideNavPath, hasTabs, parentTitle = '') => {
  for (const navItem of navData) {
    const navItemTitle = parentTitle ? `${navItem.title} - ${parentTitle}` : navItem.title
    if (getSideNavPath(navItem.path, hasTabs) === sideNavPath) {
      return navItemTitle
    }
    if (Array.isArray(navItem.items)) {
      const title = getPageTitle(navItem.items, sideNavPath, hasTabs, navItemTitle)
      if (title) {
        return title
      }
    }
  }
}

```

2023-01-31 00:00 UTC, francinelucca commented on services/web-app/components/mdx-page/mdx-page.js
> +  })
Tabs can be not supplied: https://github.com/carbon-design-system/carbon-platform/blob/main/services/web-app/pages/libraries/%5Bhost%5D/%5Borg%5D/%5Brepo%5D/%5Blibrary%5D/%5Bref%5D/assets/%5Basset%5D/%5Btab%5D.js#L86
```suggestion
  const tabsData = tabs?.map((tab) => {
    if (tab?.name && tab?.path) {
      return tab
    }
    const tabSlug = slugify(tab, { strict: true, lower: true })
    return {
      name: tab,
      path: baseSegment ? `/${baseSegment}/${tabSlug}` : `/${tabSlug}`
    }
  })
```

2023-01-31 16:59 UTC, mattrosno commented
@carbon-design-system/carbon-platform-devs this seems to be working great with @francinelucca's changes. I think I hit every page and the meta titles are working. If you want to test all pages in a library at a version to see that in the meta title:

http://localhost:3000/libraries/carbon-react/v11.21.0

2023-01-31 18:31 UTC, francinelucca approved these changes
🚀

2023-02-01 16:30 UTC, alisonjoseph approved these changes
LGTM!

2023-02-01 16:30 UTC, merged