feat: simplify asset inheritance
carbon-design-system/carbon-platform pull request #271
Opened 2022-02-22 17:20 UTC by mattrosno

Closes #126 

{{ Short description }}

#### Changelog

**New**

- {{ New thing }}

**Changed**

- {{ Changed thing }}

**Removed**

- {{ Removed thing }}

#### Testing / reviewing

{{ Add descriptions, steps or a checklist for how reviewers can verify this PR works or not }}

2022-02-23 22:01 UTC, francinelucca requested changes
Nice code cleanup!! Just one comment on typeDefs and observation:
- Component cards don't seem to be punching out to external urls anymore, it's going to the detail page instead, intentional?

2022-02-23 22:17 UTC, francinelucca commented on packages/schemas/carbon-resources.schema.json
> +        "inherits ": {
```suggestion
        "inherits": {
```

2022-02-24 01:09 UTC, mattrosno commented on services/web-app/types.js
> -  private: PropTypes.bool,
Done!

2022-02-24 01:14 UTC, mattrosno commented
> * Component cards don't seem to be punching out to external urls anymore, it's going to the detail page instead, intentional?

@francinelucca intentional - my original indexing of Carbon for IBM.com inherited `externalDocsUrl` everywhere. See https://github.ibm.com/matt-rosno/carbon-for-ibm-dotcom/search?q=externalDocsUrl&unscoped_q=externalDocsUrl

After thinking through this, it doesn't make much sense for that to be inheritable by default. I don't expect external docs to be the same for all sibling-framework implementations by default.

Maybe during our initial indexing that will result in some duplicate `externalDocsUrl` values, but that'll just be temporarily until we can remove those across all libraries/assets when we're able to do final migration and sunset legacy sites.

2022-02-24 01:19 UTC, francinelucca approved these changes

2022-02-24 15:20 UTC, merged