feat: add mdx
carbon-design-system/carbon-platform pull request #340
Opened 2022-03-08 19:07 UTC by alisonjoseph

2022-03-09 22:18 UTC, alisonjoseph commented on services/web-app/components/autolink-header/autolink-header.js
> +import React from 'react'
getting a bunch of other errors now 😅

2022-03-10 13:42 UTC, alisonjoseph commented
@jdharvey-ibm getting a bunch of linting errors now unrelated to any files I've touched.

2022-03-10 15:26 UTC, francinelucca commented
I believe linting erros are due to adding ` '@typescript-eslint/no-use-before-define': 'error',` to rules in `.eslintrc.js` , do we want to enforce no usage before defining? if so we probably just need to update all those files that are not compliant and basically move everything around. I can help if that's what we want to do. @jdharvey-ibm @alisonjoseph

2022-03-10 16:18 UTC, francinelucca requested changes
Minor comments, everything else LGTM
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/40550942/157706994-010d963f-604b-4cb9-8c6d-73e357cecf6a.png">
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/40550942/157707059-9b4d223a-7301-43e3-a498-6cbeaade5a98.png">
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/40550942/157707103-5f9ec8ea-f2d2-4289-9490-b465b87b030d.png">

2022-03-10 16:18 UTC, francinelucca commented on services/web-app/package.json
> +    "@next/mdx": "^12.1.0",
duplicate dependencies here 
"@mdx-js/loader": "^2.0.0",
    "@next/mdx": "^12.1.0",

2022-03-10 16:28 UTC, alisonjoseph commented on services/web-app/components/markdown/markdown.module.scss
> +/* TODO: pull in nested list prop diredtly from core Carbon for correct bullets */
created issue #351

2022-03-10 16:28 UTC, alisonjoseph commented on services/web-app/components/mdx/components.js
> +  /* TODO: get nested lists working
created issue #351

2022-03-10 16:36 UTC, francinelucca approved these changes
🎉

2022-03-10 18:14 UTC, jdharvey-ibm approved these changes

2022-03-14 14:13 UTC, merged