feat(web-app): #499 next/image support for mdx
carbon-design-system/carbon-platform pull request #546
Opened 2022-04-12 17:02 UTC by francinelucca

Closes #499 

#### Testing / reviewing

Add file `test.mdx` under `services/web-app/pages` containing:
`![alt](/carbon.png)`.

Make sure you're able to access "http://localhost:3000/test", that it renders the image and that it resizes as the screen width changes

2022-04-12 18:38 UTC, alisonjoseph requested changes
Yay! This is working awesome 🥳 , lets pull the image out into its own component just to keep things cleaner.

2022-04-13 15:29 UTC, francinelucca commented
> Yay! This is working awesome 🥳 , lets pull the image out into its own component just to keep things cleaner.

Done!

2022-04-13 16:34 UTC, alisonjoseph submitted a review, later dismissed
🔥

2022-04-13 16:34 UTC, alisonjoseph commented on services/web-app/components/mdx/components.js
> +import Image from '../markdown/image'
```suggestion
import Image from '@/components/markdown/image'
```
super small nitpick

2022-04-13 20:55 UTC, andreancardona approved these changes
Looks good! There is that alt prop warning but I know not sure if that's needed since we have it in the Image component - thoughts?

2022-04-13 21:07 UTC, alisonjoseph approved these changes

2022-04-13 21:08 UTC, alisonjoseph commented
I think we can safely ignore that warning @andreancardona 👍

2022-04-13 21:08 UTC, merged