feat(web-app): migrate article card component for mdx
carbon-design-system/carbon-platform pull request #579
Opened 2022-04-18 14:45 UTC by alisonjoseph

Blocked by #575 (waiting on remark-unwrap-images)

Closes #539 

Migrates ArticleCard component from Gatsby theme

#### Testing / reviewing
http://localhost:3000/mdx/article-card

https://gatsby-theme-carbon.vercel.app/components/ArticleCard

2022-04-18 19:52 UTC, francinelucca approved these changes, later dismissed
LGTM!

2022-04-18 19:52 UTC, francinelucca commented on services/web-app/components/article-card/article-card.module.scss
> +  @include type.type-style('body-short-02');
```suggestion
  @include type.type-style('body-compact-02');
```
should this be `body-compact-02` instead in v11?

2022-04-18 20:00 UTC, francinelucca submitted a review, later dismissed

2022-04-20 19:01 UTC, francinelucca requested changes
LGTM! minor change request

2022-04-20 19:08 UTC, francinelucca approved these changes
🎉

2022-04-20 19:21 UTC, andreancardona approved these changes

2022-04-20 19:21 UTC, merged