feat: add aside mdx component
carbon-design-system/carbon-platform pull request #592
Opened 2022-04-20 19:48 UTC by alisonjoseph

Closes #532 

#### Testing / reviewing

http://localhost:3000/mdx/aside
https://gatsby-theme-carbon.vercel.app/components/Aside

**Note:** The new grid doesn't support offset columns in the middle of a "row", so we will have to update grid mdx slightly for the one page on the Carbon website (inside of data viz) using this component.

2022-04-20 20:37 UTC, francinelucca requested changes

2022-04-20 20:37 UTC, francinelucca commented on services/web-app/components/aside/index.js
> + * Copyright IBM Corp. 2021, 2022
```suggestion
 * Copyright IBM Corp. 2022, 2022
```

2022-04-20 20:37 UTC, francinelucca commented on services/web-app/components/aside/aside.js
> + * Copyright IBM Corp. 2021, 2022
```suggestion
 * Copyright IBM Corp. 2022, 2022
```

2022-04-20 22:39 UTC, francinelucca commented on services/web-app/components/aside/aside.module.scss
> + * Copyright IBM Corp. 2021, 2022
```suggestion
 * Copyright IBM Corp. 2022, 2022
```

2022-04-20 22:42 UTC, francinelucca approved these changes
👯

2022-04-21 22:42 UTC, andreancardona approved these changes

2022-04-21 22:43 UTC, merged