feat(web-app): add preview mdx component
carbon-design-system/carbon-platform pull request #623
Opened 2022-04-25 15:48 UTC by alisonjoseph

Closes #613

#### Testing / reviewing

http://localhost:3000/mdx/preview
https://carbondesignsystem.com/developing/react-tutorial/step-4/

2022-04-25 21:55 UTC, francinelucca approved these changes, later dismissed
🚀 
<img width="1258" alt="image" src="https://user-images.githubusercontent.com/40550942/165181483-dbac14ae-50d9-4884-a25c-08443930c830.png">

2022-04-26 14:13 UTC, francinelucca approved these changes, later dismissed

2022-04-27 15:51 UTC, francinelucca requested changes
Looks good, minor suggestions

2022-04-27 15:51 UTC, francinelucca commented on services/web-app/components/preview/preview.js
> +
```suggestion

Preview.propTypes = {
  title: Proptypes.string
}

```

2022-04-27 15:51 UTC, francinelucca commented on services/web-app/stories/mdx/preview.stories.js
> +  parameters: {}
```suggestion
  parameters: {},
  argTypes: {
    title: {
      control: false
    }
  }
```

2022-04-28 15:25 UTC, francinelucca approved these changes, later dismissed

2022-04-28 19:28 UTC, andreancardona approved these changes, later dismissed

2022-04-29 21:45 UTC, francinelucca submitted a review, later dismissed
🎉

2022-05-04 16:54 UTC, andreancardona approved these changes
🔥

2022-05-04 16:55 UTC, francinelucca approved these changes

2022-05-04 16:55 UTC, merged