feat: carbon angular index test
carbon-design-system/carbon-platform pull request #667
Opened 2022-04-28 03:16 UTC by andreancardona

Closes #514 

Indexing PR: 
https://github.com/IBM/carbon-components-angular/pull/2081/files

## Testing / reviewing
Run the app locally you should see `carbon components angular` listed as a library:

2022-04-28 15:51 UTC, francinelucca requested changes
comments on https://github.com/IBM/carbon-components-angular/pull/2081

2022-04-28 15:51 UTC, francinelucca commented on services/web-app/data/libraries.js
> +  // },
```suggestion
  // 'carbon-components-angular': {
  //   host: 'github.com',
  //   org: 'carbon-design-system',
  //   repo: 'carbon-components-angular',
  //   path: '/src',
  //   group: carbonComponentsGroup
  // },
```

2022-05-03 15:32 UTC, francinelucca reviewed
LGTM!

2022-05-04 15:43 UTC, alisonjoseph approved these changes, later dismissed

2022-05-04 20:24 UTC, alisonjoseph approved these changes, later dismissed

2022-05-05 18:26 UTC, alisonjoseph approved these changes

2022-05-06 01:14 UTC, francinelucca approved these changes
LGTM!! 🎉

2022-05-06 04:48 UTC, merged