feat: add of mdx components to storybook
carbon-design-system/carbon-platform pull request #669
Opened 2022-04-28 19:39 UTC by alisonjoseph

Closes #644, Closes #651, Closes #655, Closes #646, Closes #645, Closes #654

Document MDX components in Storybook

#### Changelog

- Caption
- Title
- PageDescription
- ResourceCard
- Aside,
- InlineNotification

#### Testing / reviewing

http://localhost:6006/

2022-05-05 19:58 UTC, andreancardona approved these changes, later dismissed

2022-05-06 02:41 UTC, francinelucca requested changes
any reason for moving this file?:
 services/web-app/scripts/create-local-certificates.sh  -> services/web-app/stories/scripts/create-local-certificates.sh

2022-05-06 02:41 UTC, francinelucca commented on services/web-app/components/art-direction/art-direction1.js
> +/*
do we need an art-direction.js and an art-direction1.js?

2022-05-06 02:41 UTC, francinelucca commented on services/web-app/stories/mdx/dondont.stories.js
> +/*
rename:

services/web-app/stories/mdx/dondont.stories.js -> services/web-app/stories/mdx/dodont.stories.js

2022-05-06 02:58 UTC, francinelucca reviewed
Suggestions for controls we might not want to show on SB

2022-05-06 02:58 UTC, francinelucca commented on services/web-app/stories/mdx/art-direction.stories.js
> +  component: ArtDirection
```suggestion
  component: ArtDirection,
    argTypes: {
    children: {
      control: false
    }
  }
```

2022-05-06 02:58 UTC, francinelucca commented on services/web-app/stories/mdx/article-card.stories.js
> +  component: ArticleCard
```suggestion
  component: ArticleCard,
     argTypes: {
    children: {
      control: false
    },
    className: {
    control: false
    
    }
    }
```

2022-05-06 02:58 UTC, francinelucca commented on services/web-app/stories/mdx/aside.stories.js
> +  component: Aside
```suggestion
  component: Aside,
     argTypes: {
    children: {
      control: false
    },
    className: {
    control: false
    
    }
    }
```

2022-05-06 02:58 UTC, francinelucca commented on services/web-app/stories/mdx/dondont.stories.js
> +  subcomponents: { DoDont }
```suggestion
  subcomponents: { DoDont },
     argTypes: {
    children: {
      control: false
    },
    className: {
    control: false
    
    }
    }
```

2022-05-06 02:58 UTC, francinelucca commented on services/web-app/stories/mdx/gif-player.stories.js
> +  component: GifPlayer
```suggestion
  component: GifPlayer,
     argTypes: {
    children: {
      control: false
    },
    className: {
    control: false
    
    }
    }
```

2022-05-06 02:58 UTC, francinelucca commented on services/web-app/stories/mdx/inline-notification.stories.js
> +  component: InlineNotification
```suggestion
  component: InlineNotification,
     argTypes: {
    children: {
      control: false
    },
    className: {
    control: false
    
    }
    }
```

2022-05-06 02:58 UTC, francinelucca commented on services/web-app/stories/mdx/page-description.stories.js
> +  component: PageDescription
```suggestion
  component: PageDescription,
     argTypes: {
    children: {
      control: false
    },
    className: {
    control: false
    
    }
    }
```

2022-05-06 02:58 UTC, francinelucca commented on services/web-app/stories/mdx/profile.stories.js
> +  component: Profile
```suggestion
  component: Profile,
     argTypes: {
    children: {
      control: false
    }
    }
```

2022-05-06 02:58 UTC, francinelucca commented on services/web-app/stories/mdx/resource-card.stories.js
> +  component: ResourceCard
```suggestion
  component: ResourceCard,
     argTypes: {
    children: {
      control: false
    },
    className: {
    control: false
    
    }
    }
```

2022-05-06 02:58 UTC, francinelucca commented on services/web-app/stories/mdx/tabs.stories.js
> +  subcomponents: { Tab }
```suggestion
  subcomponents: { Tab },,
     argTypes: {
    children: {
      control: false
    }
    }
```

2022-05-06 02:58 UTC, francinelucca commented on services/web-app/stories/mdx/title.stories.js
> +  component: Title
```suggestion
  component: Title,,
     argTypes: {
    children: {
      control: false
    },
    className: {
    control: false
    
    }
    }
```

2022-05-06 02:58 UTC, francinelucca commented on services/web-app/stories/mdx/video.stories.js
> +  component: Video
```suggestion
  component: Video,
     argTypes: {
    children: {
      control: false
    },
    src: {
    control: false
    },
    poster: {
    control: false
    }
    }
```

2022-05-06 15:01 UTC, francinelucca approved these changes
👨‍🍳 💋

2022-05-06 19:09 UTC, merged