fix: fix tabs sticky and mobile bug
carbon-design-system/carbon-platform pull request #671
Opened 2022-04-29 06:19 UTC by andreancardona

Closes #505   &  #643 

- This PR makes sure tabs are sticky 
- It also makes sure the sudo element expands full vw at all. breakpoints

NOTE: thank you @francinelucca for helping me on this one!!  💯 

## TESTING:

- [ ] make sure sticky tabs stay sticky
- [ ] make sure there are no visual regressions with tabs at any breakpoint

2022-04-29 21:08 UTC, francinelucca requested changes
minor CRs.

it doesn't look like our calculations are working for the line span on max breakpoint 😢 , let's sync on monday 
<img width="1772" alt="image" src="https://user-images.githubusercontent.com/40550942/166069349-97249cd6-7867-46a1-a987-63e15016d52b.png">

2022-04-29 21:08 UTC, francinelucca commented on services/web-app/pages/assets/[host]/[org]/[repo]/[library]/[ref]/[asset].module.scss
> +  z-index: 9000;
you can import like: `@use '@carbon/react/scss/utilities/z-index' as z-index;`
```suggestion
  z-index: z-index.z('overlay');;
```

2022-05-03 18:26 UTC, francinelucca approved these changes
💃

2022-05-03 18:54 UTC, alisonjoseph approved these changes
🔥

2022-05-03 18:54 UTC, merged