feat(web-app): mdx icon component
carbon-design-system/carbon-platform pull request #681
Opened 2022-05-03 19:06 UTC by francinelucca

Closes #567 

- I'm thinking we don't need a Storybook for this? I can add one if otherwise
- I left the icons inside the comp folder, should they go on @carbon-platform//icons instead?

#### Testing / reviewing

http://localhos:3000/mdx/mdx-icon
https://carbondesignsystem.com/#other-resources (see icons on cards)

2022-05-03 21:56 UTC, alisonjoseph requested changes
I think it would probably make sense to add these images to our icon package, most are used multiple times throughout the Carbon website. I also think I would add a story for this, so anyone adding content could easily see which icons were already part of the site?

2022-05-05 16:34 UTC, alisonjoseph commented on services/web-app/components/mdx-icon/mdx-icon.js
> +  color: PropTypes.oneOf(Object.keys(iconColor)),
should we add a comment for this prop?

2022-05-05 18:56 UTC, andreancardona approved these changes, later dismissed

2022-05-06 15:51 UTC, alisonjoseph approved these changes

2022-05-06 19:09 UTC, merged