refactor(web-app): replace spacing tokens with rem function for height and width
carbon-design-system/carbon-platform pull request #717
Opened 2022-05-11 19:11 UTC by alisonjoseph

Closes #572 

#### Changelog

**Changed**

- Update all height/width pixel values to use rem function
- Convert spacing tokens to pixel values for height/width

#### Testing / reviewing
 
Nothing should visually change 🙏

2022-05-12 19:08 UTC, francinelucca requested changes
Also looks like we're missing some on:
- services/web-app/components/aside/aside.module.scss (L44)
- services/web-app/components/catalog-multislect-filter/catalog-multiselect-filter.module.scss (L102,106,142)
- services/web-app/components/color-palette/color-palette.module.scss (L167)
- services/web-app/components/color-token-table/color-token-table.module.scss (L31)
- services/web-app/components/svg-libraries/svg-library.module.scss (L54, 58,96,302)
- services/web-app/pages/assets/index/index.module.scss (L26)
- services/web-app/styles/vendor/_overrides.scss (L35)

2022-05-12 22:17 UTC, alisonjoseph commented on services/web-app/components/catalog-multislect-filter/catalog-multiselect-filter.module.scss
> +  min-width: convert.rem(18px);
yep!

2022-05-12 22:25 UTC, alisonjoseph commented
@francinelucca thanks! Fixed the missing values, also left anything at 1px that was a border. (for example L26 in /assets/index/index.module.scss )

2022-05-13 22:11 UTC, francinelucca approved these changes
LGTM! 💃 ✨

2022-05-15 15:34 UTC, andreancardona reviewed
How do we feel about the page header height in `page-header.module.scss`? Should this be converted as well?

<img width="798" alt="Screen Shot 2022-05-15 at 10 32 33 AM" src="https://user-images.githubusercontent.com/32720851/168480877-c29da931-b5eb-48ef-a466-9bfcc9869c36.png">

2022-05-16 13:03 UTC, alisonjoseph commented
@andreancardona that line was removed in #715 that was just merged, I'll update the branch and double check things.

2022-05-16 14:25 UTC, andreancardona approved these changes
🔥

2022-05-16 14:25 UTC, merged