Scrub mdx 692
carbon-design-system/carbon-platform pull request #740
Opened 2022-05-17 22:04 UTC by alisonjoseph

Closes #692

#### Changelog

**New**

- {{ New thing }}

**Changed**

- {{ Changed thing }}

**Removed**

- {{ Removed thing }}

#### Testing / reviewing

{{ Add descriptions, steps or a checklist for how reviewers can verify this PR works or not }}

2022-05-19 14:54 UTC, andreancardona submitted a review, later dismissed
🔥 tested locally looks good!

2022-05-19 19:25 UTC, francinelucca submitted a review, later dismissed
✨

2022-05-20 21:10 UTC, jdharvey-ibm commented
@francinelucca and I are going to work on splitting this out into its own package so we can hammer it with unit tests! 🔨

2022-05-23 15:39 UTC, alisonjoseph commented
@francinelucca found another page that "breaks"
https://github.com/carbon-design-system/carbon-website/blob/main/src/pages/help/contact-us/index.mdx

> ./pages/assets/contact/index.mdx
Unexpected character `@` (U+0040) in name, expected a name character such as letters, digits, `$`, or `_`; whitespace before attributes; or the end of the tag (note: to create a link in MDX, use `[text](url)`)

```
The Carbon team can also be reached on Twitter:
[@\_carbondesign](https://twitter.com/_carbondesign?lang=en)
```

2022-06-02 16:55 UTC, alisonjoseph reviewed
Approved 😉 

✅

2022-06-03 06:01 UTC, jdharvey-ibm requested changes

2022-06-03 06:01 UTC, jdharvey-ibm commented on services/web-app/lib/github.js
> +  let serializedContent = null
MDX modification logic should all be moved out of this file and into the sanitizer plugin.

The github file should only be responsible for retrieving data from github.com. It should not peek at (or modify) its contents in any form.

There likely needs to be a separate module or component whose responsibility is to call the github.js functions to obtain the data, set up a remark instance with all of the plugins, and produce sanitized mdx as output.

2022-06-07 20:19 UTC, francinelucca commented
closing: we're starting over

2022-06-07 20:19 UTC, closed without merging