feat: mobile nav bugs
carbon-design-system/carbon-platform pull request #749
Opened 2022-05-19 14:29 UTC by andreancardona

Closes #504 

Side Nav: 
- [x] We need to close the mobile navigation when you click outside of the menu (the backdrop)
- [x] We need to close the side nav on mobile when you click any of the links in the side nav
- [x] With a short viewport, we can't scroll to the bottom of the side nav

Library Side Nav: 
- [x] We need to close the mobile navigation when you click outside of the menu (the backdrop)
- [x] We need to close the side nav on mobile when you click any of the links in the side nav
- [x] With a short viewport, we can't scroll to the bottom of the side nav

## TESTING: 

- test side nav at `sm` & `md` breakpoints: http://localhost:3000/assets/components
- test lib side nav at `sm` & `md` breakpoints: http://localhost:3000/assets/carbon-charts

2022-05-24 23:10 UTC, francinelucca requested changes
LGTM! minor comment

2022-05-25 17:37 UTC, alisonjoseph approved these changes
LGTM!

2022-05-25 17:37 UTC, alisonjoseph commented on package-lock.json
> +}
is this intentional?

2022-05-25 22:42 UTC, francinelucca approved these changes
💃

2022-05-27 16:25 UTC, merged