feat: add library asset description
carbon-design-system/carbon-platform pull request #771
Opened 2022-05-23 18:46 UTC by andreancardona

Closes #558 

Adds the PageDescription component as follows:

breakpoints: sm={4} md={6} lg={8} - like the other carbon pages: https://carbondesignsystem.com/all-about-carbon/what-is-carbon/

<img width="1543" alt="Screen Shot 2022-05-23 at 1 42 53 PM" src="https://user-images.githubusercontent.com/32720851/169885715-4d53c28c-47c9-4de6-9f08-21eebd4db981.png">

Testing: http://localhost:3000/assets/carbon-charts

2022-05-23 18:59 UTC, alisonjoseph requested changes
LGTM other than one tiny change! I don't think we need the class name?

2022-05-23 18:59 UTC, alisonjoseph commented on services/web-app/pages/assets/[host]/[org]/[repo]/[library]/[ref]/index.js
> +          <PageDescription className={styles.description}>{seo.description}</PageDescription>
```suggestion
          <PageDescription>{seo.description}</PageDescription>
```

2022-05-23 19:15 UTC, alisonjoseph approved these changes
🚀

2022-05-24 22:56 UTC, francinelucca approved these changes
👩‍🍳 💋 !

2022-05-25 15:10 UTC, merged