feat: filter data table draft
carbon-design-system/carbon-platform pull request #842
Opened 2022-06-07 19:47 UTC by andreancardona

Closes #756 

DRAFT DO NOT MERGE

closing out the other draft PR: https://github.com/carbon-design-system/carbon-platform/pull/791

- Reason: merge conflicts got MESSY

2022-08-11 21:53 UTC, alisonjoseph requested changes
This is looking good! Couple small things

2022-08-11 21:53 UTC, alisonjoseph commented on services/web-app/components/filterable-design-kit-table/filterable-design-kit-table.module.scss
> +@use '@carbon/react/scss/utilities/convert' as convert;
```suggestion
```

We should be able to remove these

2022-08-11 21:53 UTC, alisonjoseph commented on services/web-app/components/filterable-design-kit-table/filterable-design-kit-table.module.scss
> + * Copyright IBM Corp. 2021, 2022
```suggestion
 * Copyright IBM Corp. 2022, 2022
```

2022-08-11 21:53 UTC, alisonjoseph commented on services/web-app/components/filterable-design-kit-table/filterable-design-kit-table.js
> + * Copyright IBM Corp. 2021, 2022
```suggestion
 * Copyright IBM Corp. 2022, 2022
```

2022-08-11 21:53 UTC, alisonjoseph commented on services/web-app/components/filterable-design-kit-table/index.js
> + * Copyright IBM Corp. 2021, 2022
```suggestion
 * Copyright IBM Corp. 2022, 2022
```

2022-08-11 21:53 UTC, alisonjoseph commented on services/web-app/data/nav-data.js
> +  },
```suggestion
```
I don't think we need this?

2022-08-11 21:53 UTC, alisonjoseph commented on services/web-app/components/filterable-design-kit-table/filterable-design-kit-table.js
> +  )
linting is yelling about this

2022-08-11 22:01 UTC, alisonjoseph commented on services/web-app/components/filterable-design-kit-table/filterable-design-kit-table.js
> +  // only render the firt maintainer within the respective group
```suggestion
  // only render the first maintainer within the respective group
```

2022-08-11 22:10 UTC, alisonjoseph approved these changes
LGTM

2022-08-11 23:03 UTC, francinelucca requested changes
visuals LGTM, CR suggestion and there seems to be a re-render error, see browser console: 

<img width="492" alt="image" src="https://user-images.githubusercontent.com/40550942/184256626-31c6976f-468f-4b4c-84cc-44dcd4f13157.png">

Could be related to useEffect(), not sure what the specific issue is here

2022-08-12 15:59 UTC, francinelucca approved these changes
👯‍♀️

2022-08-12 16:08 UTC, merged