feat: expressive list from gatsby
carbon-design-system/carbon-platform pull request #872
Opened 2022-06-13 09:55 UTC by andreancardona

Closes #777 

### TEST:

- http://localhost:3000/mdx/expressive-list
- https://gatsby-theme-carbon.vercel.app/components/ExpressiveList

2022-06-13 14:36 UTC, francinelucca reviewed
minor comment, also, should we add this to `index.mdx` and add a storybook as well?

2022-06-13 14:36 UTC, francinelucca commented on services/web-app/components/expressive-list/expressive-list.module.scss
> +:global(.cds--subgrid .cds--subgrid--wide) {
```suggestion
// carbon override subgrid
:global(.cds--subgrid .cds--subgrid--wide) {
```

2022-06-15 14:13 UTC, francinelucca commented on services/web-app/components/divider/divider.module.scss
> +:global(.cds--subgrid--wide) {
```suggestion
// override carbon grid
:global(.cds--subgrid--wide) {
```

2022-06-15 17:30 UTC, francinelucca requested changes
looks good visually.  some comments + need to fix CI checks

2022-06-15 17:30 UTC, francinelucca commented on services/web-app/pages/mdx/index.mdx
> +    <
what's happening here? 😅  this is breaking the mdx page for me 
<img width="1212" alt="image" src="https://user-images.githubusercontent.com/40550942/173887633-94d9683e-a2e5-494c-8e28-337b214d3809.png">

2022-06-15 17:30 UTC, francinelucca commented on services/web-app/stories/mdx/divider.stories.js
> +}
Let's hide these controls, they don't make much sense? 
<img width="1240" alt="image" src="https://user-images.githubusercontent.com/40550942/173887863-23b23b43-0bfd-407e-9ab0-ff1ed893108e.png">

```suggestion
  title: 'MDX/Divider',
  component: Divider,,
  argTypes: {
    children: {
      control: false
    },
    className: {
      control: false
    }
  }
}
```

2022-06-15 18:26 UTC, alisonjoseph requested changes
I think you need to run `npm run lint:fix` for the linting error

2022-06-15 18:28 UTC, alisonjoseph commented on services/web-app/components/divider/divider.js
> +
You'll want to add a description here that will show up in storybook

```
/**
 * The `<Divider>` component is a wrapper component that adds a top border
 * and spacing to divide sections of content.
 */
```

Or something like that

2022-06-15 18:35 UTC, alisonjoseph commented on services/web-app/components/divider/divider.module.scss
> +  border-top: 1px solid theme.$border-strong;
```suggestion
  padding-top: spacing.$spacing-07;
  border-top: 1px solid theme.$border-strong;
  margin-top: calc(spacing.$spacing-09 + spacing.$spacing-03);
```

suggestion to get correct spacing above the first element

2022-06-15 18:37 UTC, alisonjoseph commented
@andreancardona I added this component to the meetups page to test and pushed to this branch http://localhost:3000/about-carbon/meetups

2022-06-15 18:40 UTC, alisonjoseph commented on services/web-app/pages/mdx/index.mdx
> +    <
```suggestion
    <ArticleCard
```

2022-06-17 17:25 UTC, francinelucca reviewed
1 - Border top seems longer in width in next.carbondesignsystem.com , are we ok with that? 
2 - Do we want to add this to http://localhost:3000/about-carbon/how-carbon-works, http://localhost:3000/assets as well?

other than that lgtm

2022-06-17 18:36 UTC, alisonjoseph requested changes
LGTM other than the right margin/padding Francine pointed out

2022-06-17 18:36 UTC, alisonjoseph commented on services/web-app/components/divider/divider.module.scss
> +  margin-bottom: calc(spacing.$spacing-09 + spacing.$spacing-03);
```suggestion
  padding: spacing.$spacing-04 spacing.$spacing-05 0 0;
  border-top: 1px solid theme.$border-strong;
  margin-right: -(spacing.$spacing-05);
  margin-bottom: calc(spacing.$spacing-09 + spacing.$spacing-03);
```

@francinelucca with the eagle eyes! you're correct its 1rem off on the right, this should fix. 

It wouldn't let me do shorthand for margin with the negative value in the middle 🤷‍♀️

2022-06-17 19:02 UTC, alisonjoseph approved these changes

2022-06-17 19:34 UTC, alisonjoseph commented on services/web-app/components/divider/divider.module.scss
> +  @include breakpoint.breakpoint(md) {
```suggestion
  @include breakpoint.breakpoint(lg) {
```

2022-06-17 21:19 UTC, francinelucca approved these changes
💃

2022-06-17 21:25 UTC, merged