feat: index ibm cognitive security
carbon-design-system/carbon-platform pull request #914
Opened 2022-06-22 21:42 UTC by andreancardona

Closes #730 

DRAFT

2022-06-23 14:09 UTC, alisonjoseph commented
Looks like patterns and templates aren't displaying? Is this a bug with our platform, or something with indexing?

2022-06-23 15:32 UTC, andreancardona commented
> Looks like patterns and templates aren't displaying? Is this a bug with our platform, or something with indexing?

Yeah I couldn't figure out why 🤔 going to ask Matt about that

2022-06-24 17:06 UTC, francinelucca reviewed
Looks good to me! verified components, patters and template 🎉 , added minor suggestions on repo PR

2022-06-28 02:14 UTC, alisonjoseph commented
This one is looking good to me too now 👍

2022-07-07 19:58 UTC, alisonjoseph commented
LGTM other than the one missing thumbnail you already mentioned 😄 
<img width="649" alt="Screen Shot 2022-07-07 at 2 57 53 PM" src="https://user-images.githubusercontent.com/2753488/177861209-43e02106-92aa-43a0-bb27-b9052ccef79e.png">

2022-07-07 20:17 UTC, francinelucca requested changes, later dismissed
LGTM ✨  except for stack-notification not showing thumbnail (think we need to rename svg to `stacked-notification`). 
Also I don't think we should push these cached files from `andreancardona` org, can we remove them.
Also left some CRs on repo pr

2022-07-13 18:14 UTC, alisonjoseph requested changes, later dismissed
I can see the components in the list

<img width="1246" alt="Screen Shot 2022-07-13 at 1 12 47 PM" src="https://user-images.githubusercontent.com/2753488/178802405-6fa3448a-d931-4426-acdf-733da0ef3174.png">

howver if I do a filter by Security I don't see any components?

<img width="1182" alt="Screen Shot 2022-07-13 at 1 13 34 PM" src="https://user-images.githubusercontent.com/2753488/178802512-00b525f4-a647-4f72-911c-5ec14a9f4268.png">

2022-07-13 18:15 UTC, alisonjoseph commented on services/web-app/data/libraries.mjs
> +    sponsor: 'ibm-security',
```suggestion
    maintainer: 'ibm-security',
```

2022-07-13 19:36 UTC, alisonjoseph approved these changes
LGTM! I see all components with their thumbnails now.

2022-07-13 19:43 UTC, francinelucca reviewed
LGTM!

2022-07-14 15:13 UTC, francinelucca approved these changes
✨

2022-07-14 15:13 UTC, merged